spring.application.name=QuanLyBanVeXemPhim

server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://localhost:5432/QuanLyBanVeXemPhim
#spring.datasource.username=postgres
#spring.datasource.password=123456

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

tmdb.api.key=29524e18f583bf85ae79f47d34ff3c91
tmdb.api.base-url=https://api.themoviedb.org/3

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}